// Project imports:
import 'package:words625/core/utils.dart';

final spanishJson = {
  "Animal (Animal)": {
    "dog": "perro",
    "cat": "gato",
    "fish": "pez",
    "bird": "pájaro",
    "cow": "vaca",
    "pig": "cerdo",
    "mouse": "ratón",
    "horse": "caballo",
    "wing": "ala",
    "animal": "animal"
  },
  "Transportation (Transporte)": {
    "train": "tren",
    "plane": "avión",
    "car": "coche",
    "truck": "camión",
    "bicycle": "bicicleta",
    "bus": "autobús",
    "boat": "barco",
    "ship": "buque",
    "tire": "neumático",
    "gasoline": "gasolina",
    "engine": "motor",
    "train ticket": "boleto de tren",
    "transportation": "transporte"
  },
  "Location (Ubicación)": {
    "city": "ciudad",
    "house": "casa",
    "apartment": "apartamento",
    "street/road": "calle/carretera",
    "airport": "aeropuerto",
    "train station": "estación de tren",
    "bridge": "puente",
    "hotel": "hotel",
    "restaurant": "restaurante",
    "farm": "granja",
    "court": "tribunal",
    "school": "escuela",
    "office": "oficina",
    "room": "habitación",
    "town": "pueblo",
    "university": "universidad",
    "club": "club",
    "bar": "bar",
    "park": "parque",
    "camp": "campamento",
    "store/shop": "tienda",
    "theater": "teatro",
    "library": "biblioteca",
    "hospital": "hospital",
    "church": "iglesia",
    "market": "mercado",
    "country": "país",
    "building": "edificio",
    "ground": "suelo",
    "space": "espacio",
    "bank": "banco",
    "location": "ubicación"
  },
  "Color (Color)": {
    "red": "rojo",
    "green": "verde",
    "blue": "azul",
    "yellow": "amarillo",
    "brown": "marrón",
    "pink": "rosa",
    "orange": "naranja",
    "black": "negro",
    "white": "blanco",
    "gray": "gris",
    "color": "color"
  },
  "People (Personas)": {
    "son": "hijo",
    "daughter": "hija",
    "mother": "madre",
    "father": "padre",
    "parent": "padre/madre",
    "baby": "bebé",
    "man": "hombre",
    "woman": "mujer",
    "brother": "hermano",
    "sister": "hermana",
    "family": "familia",
    "grandfather": "abuelo",
    "grandmother": "abuela",
    "husband": "esposo",
    "wife": "esposa",
    "king": "rey",
    "queen": "reina",
    "president": "presidente",
    "neighbor": "vecino",
    "boy": "niño",
    "girl": "niña",
    "child": "niño/niña",
    "adult": "adulto",
    "human": "humano",
    "friend": "amigo",
    "victim": "víctima",
    "player": "jugador",
    "fan": "fanático",
    "crowd": "multitud",
    "person": "persona"
  },
  "Job (Profesión)": {
    "teacher": "profesor",
    "student": "estudiante",
    "lawyer": "abogado",
    "doctor": "doctor",
    "patient": "paciente",
    "waiter": "camarero",
    "secretary": "secretario(a)",
    "priest": "sacerdote",
    "police":
        "policía", // Singular refers to the force, plural refers to officers
    "army": "ejército",
    "soldier": "soldado",
    "artist": "artista",
    "author": "autor",
    "manager": "gerente",
    "reporter": "reportero",
    "actor": "actor",
    "job": "trabajo" // "Profesión" is more specific for occupation
  },
  "Society (Sociedad)": {
    "religion": "religión",
    "heaven": "cielo",
    "hell": "infierno",
    "death": "muerte",
    "medicine": "medicina",
    "money": "dinero",
    "dollar": "dólar",
    "bill": "billete", // Can also be "factura" (invoice)
    "marriage": "matrimonio",
    "wedding": "boda",
    "team": "equipo",
    "race": "raza",
    "sex": "sexo", // Can also be "género" (gender) depending on context
    "murder": "asesinato",
    "prison": "prisión",
    "technology": "tecnología",
    "energy": "energía",
    "war": "guerra",
    "peace": "paz",
    "attack": "ataque",
    "election": "elección",
    "magazine": "revista",
    "newspaper": "periódico",
    "poison": "veneno",
    "gun": "arma",
    "sport": "deporte",
    "exercise": "ejercicio",
    "ball": "pelota",
    "game": "juego",
    "price": "precio",
    "contract": "contrato",
    "drug": "droga",
    "sign": "señal", // Can also be "signo" (symbol)
    "science": "ciencia",
    "God": "Dios"
  },
  "Beverages (Bebidas)": {
    "coffee": "café",
    "tea": "té",
    "wine": "vino",
    "beer": "cerveza",
    "juice": "jugo",
    "water": "agua",
    "milk": "leche",
    "beverage": "bebida"
  },
  "Food (Comida)": {
    "egg": "huevo",
    "cheese": "queso",
    "bread": "pan",
    "soup": "sopa",
    "cake": "pastel",
    "chicken": "pollo",
    "pork": "cerdo",
    "beef": "carne de res",
    "apple": "manzana",
    "banana": "plátano",
    "orange": "naranja",
    "lemon": "limón",
    "corn": "maíz",
    "rice": "arroz",
    "oil": "aceite",
    "seed": "semilla",
    "knife": "cuchillo",
    "spoon": "cuchara",
    "fork": "tenedor",
    "plate": "plato",
    "cup": "taza",
    "breakfast": "desayuno",
    "lunch": "almuerzo",
    "dinner": "cena",
    "sugar": "azúcar",
    "salt": "sal",
    "bottle": "botella",
    "food": "comida"
  },
  "Home (Hogar)": {
    "table": "mesa",
    "chair": "silla",
    "bed": "cama",
    "dream": "sueño",
    "window": "ventana",
    "door": "puerta",
    "bedroom": "dormitorio",
    "kitchen": "cocina",
    "bathroom": "baño",
    "pencil": "lápiz",
    "pen": "bolígrafo",
    "photograph": "fotografía",
    "soap": "jabón",
    "book": "libro",
    "page": "página",
    "key": "llave",
    "paint": "pintura",
    "letter": "carta",
    "note": "nota",
    "wall": "pared",
    "paper": "papel",
    "floor": "piso",
    "ceiling": "techo",
    "roof": "tejado",
    "pool": "piscina",
    "lock": "cerradura",
    "telephone": "teléfono",
    "garden": "jardín",
    "yard": "patio",
    "needle": "aguja",
    "bag": "bolsa",
    "box": "caja",
    "gift": "regalo",
    "card": "tarjeta",
    "ring": "anillo",
    "tool": "herramienta"
  },
  "Electronics (Electrónica)": {
    "clock": "reloj",
    "lamp": "lámpara",
    "fan": "ventilador",
    "cell phone": "teléfono celular",
    "network": "red",
    "computer": "computadora",
    "program": "programa",
    "laptop": "computadora portátil",
    "screen": "pantalla",
    "camera": "cámara",
    "television": "televisión",
    "radio": "radio"
  },
  "Body (Cuerpo)": {
    "head": "cabeza",
    "neck": "cuello",
    "face": "cara",
    "beard": "barba",
    "hair": "pelo",
    "eye": "ojo",
    "mouth": "boca",
    "lip": "labio",
    "nose": "nariz",
    "tooth": "diente",
    "ear": "oreja",
    "tear": "lágrima",
    "tongue": "lengua",
    "back": "espalda",
    "toe": "dedo del pie",
    "finger": "dedo",
    "foot": "pie",
    "hand": "mano",
    "leg": "pierna",
    "arm": "brazo",
    "shoulder": "hombro",
    "heart": "corazón",
    "blood": "sangre",
    "brain": "cerebro",
    "knee": "rodilla",
    "sweat": "sudor",
    "disease": "enfermedad",
    "bone": "hueso",
    "voice": "voz",
    "skin": "piel",
    "body": "cuerpo"
  },
  "Nature (Naturaleza)": {
    "sea": "mar",
    "ocean": "océano",
    "river": "río",
    "mountain": "montaña",
    "rain": "lluvia",
    "snow": "nieve",
    "tree": "árbol",
    "sun": "sol",
    "moon": "luna",
    "world": "mundo",
    "Earth": "Tierra",
    "forest": "bosque",
    "sky": "cielo",
    "plant": "planta",
    "wind": "viento",
    "soil": "suelo",
    "flower": "flor",
    "valley": "valle",
    "root": "raíz",
    "lake": "lago",
    "star": "estrella",
    "grass": "hierba",
    "leaf": "hoja",
    "air": "aire",
    "sand": "arena",
    "beach": "playa",
    "wave": "ola",
    "fire": "fuego",
    "ice": "hielo",
    "island": "isla",
    "hill": "colina",
    "heat": "calor",
    "nature": "naturaleza"
  },
  "Materials (Materiales)": {
    "glass": "vidrio",
    "metal": "metal",
    "plastic": "plástico",
    "wood": "madera",
    "stone": "piedra",
    "diamond": "diamante",
    "clay": "arcilla",
    "dust": "polvo",
    "gold": "oro",
    "copper": "cobre",
    "silver": "plata",
    "material": "material"
  },
  "Math/Measurements (Matemáticas/Medidas)": {
    "meter": "metro",
    "centimeter": "centímetro",
    "kilogram": "kilogramo",
    "inch": "pulgada",
    "foot": "pie",
    "pound": "libra",
    "half": "mitad",
    "circle": "círculo",
    "square": "cuadrado",
    "temperature": "temperatura",
    "date": "fecha",
    "weight": "peso",
    "edge": "borde",
    "corner": "esquina"
  },
  "Misc Nouns (Sustantivos Varios)": {
    "map": "mapa",
    "dot": "punto",
    "consonant": "consonante",
    "vowel": "vocal",
    "light": "luz",
    "sound": "sonido",
    "yes": "sí",
    "no": "no",
    "piece": "pedazo",
    "pain": "dolor",
    "injury": "lesión",
    "hole": "agujero",
    "image": "imagen",
    "pattern": "patrón",
    "noun": "sustantivo",
    "verb": "verbo",
    "adjective": "adjetivo"
  },
  "Directions (Direcciones)": {
    "top": "arriba",
    "bottom": "abajo",
    "side": "lado",
    "front": "frente",
    "back": "atrás",
    "outside": "afuera",
    "inside": "adentro",
    "up": "arriba",
    "down": "abajo",
    "left": "izquierda",
    "right": "derecha",
    "straight": "recto",
    "north": "norte",
    "south": "sur",
    "east": "este",
    "west": "oeste",
    "direction": "dirección"
  },
  "Seasons (Estaciones)": {
    "Summer": "verano",
    "Spring": "primavera",
    "Winter": "invierno",
    "Fall": "otoño",
    "season": "estación"
  },
  "Numbers (Números)": {
    "0": "cero",
    "1": "uno",
    "2": "dos",
    "3": "tres",
    "4": "cuatro",
  },
  "Months (Meses)": {
    "January": "enero",
    "February": "febrero",
    "March": "marzo",
    "April": "abril",
    "May": "mayo",
    "June": "junio",
    "July": "julio",
    "August": "agosto",
    "September": "septiembre",
    "October": "octubre",
    "November": "noviembre",
    "December": "diciembre"
  },
  "Days of the Week (Días de la Semana)": {
    "Monday": "lunes",
    "Tuesday": "martes",
    "Wednesday": "miércoles",
    "Thursday": "jueves",
    "Friday": "viernes",
    "Saturday": "sábado",
    "Sunday": "domingo"
  },
  "Time (Tiempo)": {
    "year": "año",
    "month": "mes",
    "week": "semana",
    "day": "día",
    "hour": "hora",
    "minute": "minuto",
    "second": "segundo",
    "morning": "mañana",
    "afternoon": "tarde",
    "evening": "noche",
    "night": "noche",
    "time": "tiempo"
  },
  "Verbs (Verbos)": {
    "work": "trabajar",
    "play": "jugar",
    "walk": "caminar",
    "run": "correr",
    "drive": "conducir",
    "fly": "volar",
    "swim": "nadar",
    "go": "ir",
    "stop": "parar",
    "follow": "seguir",
    "think": "pensar",
    "speak": "hablar",
    "say": "decir",
    "eat": "comer",
    "drink": "beber",
    "kill": "matar",
    "die": "morir",
    "smile": "sonreír",
    "laugh": "reír",
    "cry": "llorar",
    "buy": "comprar",
    "pay": "pagar",
    "sell": "vender",
    "shoot": "disparar",
    "learn": "aprender",
    "jump": "saltar",
    "smell": "oler",
    "hear": "oir",
    "listen": "escuchar",
    "taste": "saborear",
    "touch": "tocar",
    "see": "ver",
    "watch": "mirar",
    "kiss": "besar",
    "burn": "quemar",
    "melt": "derretir",
    "dig": "cavar",
    "explode": "explotar",
    "sit": "sentarse",
    "stand": "estar de pie",
    "love": "amar",
    "pass by": "pasar",
    "cut": "cortar",
    "fight": "pelear",
    "lie down": "acostarse",
    "dance": "bailar",
    "sleep": "dormir",
    "wake up": "despertar",
    "sing": "cantar",
    "count": "contar",
    "marry": "casarse",
    "pray": "rezar",
    "win": "ganar",
    "lose": "perder",
    "mix": "mezclar",
    "stir": "remover",
    "bend": "doblar",
    "wash": "lavar",
    "cook": "cocinar",
    "open": "abrir",
    "close": "cerrar",
    "write": "escribir",
    "call": "llamar",
    "turn": "girar",
    "build": "construir",
    "teach": "enseñar",
    "grow": "crecer",
    "draw": "dibujar",
    "feed": "alimentar",
    "catch": "atrapar",
    "throw": "lanzar",
    "clean": "limpiar",
    "find": "encontrar",
    "fall": "caer",
    "push": "empujar",
    "pull": "jalar",
    "carry": "llevar",
    "break": "romper",
    "wear": "usar",
    "hang": "colgar",
    "shake": "agitar",
    "sign": "firmar",
    "beat": "golpear",
    "lift": "levantar"
  },
  "Adjectives (Adjetivos)": {
    "long": "largo",
    "short (long)": "corto", // Short relative to long
    "tall": "alto",
    "short (vs. tall)": "bajo", // Short relative to tall
    "wide": "ancho",
    "narrow": "estrecho",
    "big": "grande",
    "large": "grande",
    "small": "pequeño",
    "little": "pequeño",
    "slow": "lento",
    "fast": "rápido",
    "hot": "caliente",
    "cold": "frío",
    "warm": "tibio",
    "cool": "fresco",
    "new": "nuevo",
    "old (new)": "viejo", // Old relative to new
    "young": "joven",
    "old (young)": "viejo", // Old relative to young
    "good": "bueno",
    "bad": "malo",
    "wet": "mojado",
    "dry": "seco",
    "sick": "enfermo",
    "healthy": "saludable",
    "loud": "ruidoso",
    "quiet": "silencioso",
    "happy": "feliz",
    "sad": "triste",
    "beautiful": "hermoso",
    "ugly": "feo",
    "deaf": "sordo",
    "blind": "ciego",
    "nice": "agradable",
    "mean": "malo", // Can also be translated as "cruel" depending on context
    "rich": "rico",
    "poor": "pobre",
    "thick": "grueso",
    "thin": "delgado",
    "expensive": "caro",
    "cheap": "barato",
    "flat": "plano",
    "curved": "curvo",
    "male": "masculino",
    "female": "femenino",
    "tight": "apretado",
    "loose": "suelto",
    "high": "alto",
    "low": "bajo",
    "soft": "suave",
    "hard": "duro",
    "deep": "profundo",
    "shallow": "superficial",
    "clean": "limpio",
    "dirty": "sucio",
    "strong": "fuerte",
    "weak": "débil",
    "dead": "muerto",
    "alive": "vivo",
    "heavy": "pesado",
    "light (heavy)": "ligero", // Light relative to heavy
    "dark": "oscuro",
    "light (dark)": "claro", // Light relative to dark
    "nuclear": "nuclear",
    "famous": "famoso"
  },
  "Pronouns (Pronombres)": {
    "I": "yo",
    "you (singular)": "tú",
    "he": "él",
    "she": "ella",
    "it": "ello",
    "we": "nosotros",
    "you (plural, as in 'y'all')":
        "vosotros", // This may vary depending on region
    "they": "ellos/ellas"
  },
};

final flatSpanishLangList = flattenLanguage(spanishJson);
